CREATE DATABASE todo;

CREATE TABLE todo(
    id SERIAL NOT NULL PRIMARY_KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (id)
);